apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'user-service'
      static_configs:
      - targets: ['user-service:3001']
    - job_name: 'task-service'
      static_configs:
      - targets: ['task-service:3002']
    - job_name: 'notification-service'
      static_configs:
      - targets: ['notification-service:3003']