version: '3.8'
services:
  # Single Database
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: fft
      POSTGRES_USER: fft_owner
      POSTGRES_PASSWORD: npg_v6DPKsGm8Mfz
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Services (add these after creating Dockerfiles)
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=fft
      - DB_USER=fft_owner
      - DB_PASSWORD=npg_v6DPKsGm8Mfz

  task-service:
    build: ./services/task-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=fft
      - DB_USER=fft_owner
      - DB_PASSWORD=npg_v6DPKsGm8Mfz

  notification-service:
    build: ./services/notification-service
    ports:
      - "3003:3003"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./services/frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - task-service

volumes:
  postgres_db_data: