apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
data:
  database: dXNlcmRi  # userdb (base64)
  username: cG9zdGdyZXM=  # postgres (base64)
  password: cGFzc3dvcmQ=  # password (base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==  # your-super-secret-jwt-key (base64)